parameters:
    lsn.simple_query_executor.collector.cache_hits.class: Lsnova\Lsnova\SimpleQueryExecutorBundle\DataColletor\Collector\CacheDataCollector

services:
    lsn.simple_query_executor.collector.cache_hits:
        class: %lsn.simple_query_executor.collector.cache_hits.class%
        public: false
        tags:
            - { name: data_collector, template: "LsnovaSimpleQueryExecutorBundle:Profiler:dataCollector", id: "lsn_simple_query_executor_collector" }